# This workflow can be launch manualy or by an API call
# curl \
#  -X POST \
#  -H "Accept: application/vnd.github.v3+json" \
#  -H "Authorization: token TOKEN" \
#  https://api.github.com/repos/ORGA/REPO/actions/workflows/WORKFLOWID/dispatches \
#  -d '{"ref": "main",    "inputs": {  "terraformVersion": "0.14.6", "directory": "test2"}}'
  
# It installs the latest version of Terraform CLI, runs
# `terraform init` and `terraform plan`.
# If the apply input variable is set to true `terraform apply` will be executed.
#
# To use this workflow, you will need to complete the following setup steps.
# 0. Create a directory to host your terraform configuration file. The relative path to this directory must be set to the input variable terraformConfigurationDirectory
# 1. Create a `provider.tf` file in this directory with the google provider and `gcs` backend 
#   Example `provider.tf`:
##GOOGLE_CREDENTIAL environnement variable must be set with a json service account key
##https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
#provider "google" {
# project     = var.project
# region      = var.region
#}
#
##run terraform init -backend-config="prefix=DIRECTORY_FOR_BACKEND"
##https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration
#terraform {
#  backend "gcs" {}
#}
#
# 2. Create a `main.tf` file 
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
# 3. Create a service account key and store it in a github secret on your github Repository under the GOOGLE_CREDENTIALS key
# 4. Create a pull request


name: 'Terraform on Pull Request'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

env:
# https://www.terraform.io/docs/cli/config/environment-variables.html#tf_in_automation
  TF_IN_AUTOMATION : true
# https://www.terraform.io/docs/cli/config/environment-variables.html#tf_input  
  TF_INPUT : 0
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  terraformBackendPrefix: "default"
  apply: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}


jobs:
  terraform:
    name: 'Terraform on Pull Request'
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash
        working-directory: "${{ env.terraformConfigurationDirectory }}"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Read environment variables
      run: |
           git fetch origin environments
           git show remotes/origin/environments:default.env > default.env
    - name: Set environments variables
      uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: default.env
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "${{ env.terraformVersion }}"
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      working-directory: "${{ env.workingDirectory }}"
      continue-on-error: true
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, version.
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=${{ env.bucketName }}" -backend-config="prefix=${{ env.terraformBackendPrefix }}"
      working-directory: "${{ env.workingDirectory }}"
    - name: Terraform plan
      id: plan
      run: terraform plan -no-color
      working-directory: "${{ env.workingDirectory }}"
      continue-on-error: true
    - name: Update Pull Request
      uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`${process.env.PLAN}\`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
    - name: Terraform apply
      if: env.apply == 'true'
      run: terraform apply -auto-approve
      working-directory: "${{ env.workingDirectory }}"
